INSERT INTO Blog
VALUES
(1,N'Khách sạn Dalat Eden',N'Một khách sạn nghỉ dưỡng với khung cảnh thiên nhiên tuyệt đẹp, một khách sạn sang trọng 3 sao nằm ở trung tâm thành phố Đà Lạt. Khách sạn được xây dựng theo phong cách Pháp cổ điển và có tầm nhìn tuyệt đẹp ra hồ Xuân Hương.',N'thomong',2),
(2, N'Khách sạn Hoa Đà Lạt 3',  N'Một khách sạn nghỉ dưỡng với khung cảnh thiên nhiên tuyệt đẹp.Một khách sạn nằm ở khu vực làng hoa Đà Lạt, nơi bạn có thể tham quan các vườn hoa và mua hoa tươi.',N'binhyen',4),
(3, N'La Maison d Or', N'Một khách sạn sang trọng nằm ở trung tâm thành phố Nha Trang, với tầm nhìn tuyệt đẹp ra vịnh Nha Trang. Khách sạn có 50 phòng và suite, tất cả đều được trang bị nội thất hiện đại và tiện nghi cao cấp. Khách sạn cũng có một hồ bơi vô cực, một spa, và một nhà hàng phục vụ ẩm thực quốc tế.', N'raoi',17),
(4,N'Le Château dOr',N'Một khách sạn sang trọng nằm ở khu vực trung tâm thành phố Nha Trang. Khách sạn có 50 phòng và suite, tất cả đều được trang bị nội thất cổ điển.Tọa lạc tại thành phố Nha Trang, cách Bãi biển Nha Trang 500 m, LeMore Hotel Nha Trang cung cấp chỗ nghỉ với nhà hàng, chỗ đỗ xe riêng miễn phí, hồ bơi ngoài trời và trung tâm thể dục. Nằm trong bán kính 800 m từ Quảng trường 2/4 và chưa đầy 1 km từ Tháp Trầm Hương, chỗ nghỉ này có quầy bar và sảnh khách chung. Nơi đây cung cấp dịch vụ lễ tân 24 giờ, dịch vụ đưa đón sân bay, dịch vụ phòng và WiFi miễn phí trong toàn bộ khuôn viên.',N'thoiyen',69),
(5,N'La Perle de Jade',N'Một khách sạn sang trọng nằm ở khu vực trung tâm thành phố Nha Trang. Khách sạn có 100 phòng và suite, tất cả đều được trang bị nội thất hiện đại. Khách sạn cũng có một hồ bơi trong nhà, một spa, và một nhà hàng phục vụ ẩm thực quốc tế. Nằm ở thành phố Nha Trang, cách Bãi biển Nha Trang 350 m, Nha Trang Pearl Hotel có dịch vụ nhận phòng/trả phòng cấp tốc, phòng nghỉ không gây dị ứng, sảnh khách chung, WiFi miễn phí và sân hiên. Khách sạn 3 sao này có máy ATM và dịch vụ tiền sảnh. Chỗ nghỉ cung cấp dịch vụ lễ tân 24 giờ, dịch vụ phòng và dịch vụ thu đổi ngoại tệ cho khách. Phòng nghỉ tại Nha Trang Pearl Hotel được trang bị tủ để quần áo, TV màn hình phẳng, máy điều hòa, minibar và phòng tắm riêng với vòi sen cùng dép. Một số phòng có ban công. ',N'mongngien',70),
(6,N'InterContinental Resort Phan Thiet', N'InterContinental Resort Phan Thiet là một khu nghỉ dưỡng sang trọng nằm trên Bãi biển Phan Thiết. Khu nghỉ dưỡng có 500 phòng và suite, tất cả đều được trang bị nội thất hiện đại. InterContinental Resort Phan Thiet cũng có một hồ bơi ngoài trời, một spa, và một nhà hàng phục vụ ẩm thực quốc tế.Khu nghỉ dưỡng có một nhà hàng phục vụ các món ăn quốc tế và một quầy bar. Khu nghỉ dưỡng cũng có một hồ bơi vô cực, một spa và một phòng tập thể dục.',N'tsun',80),
(7,N'Nhà nghỉ Bãi Trước', N'Nhà nghỉ Bãi Trước là một nhà nghỉ bình dân nằm ở trung tâm thành phố Vũng Tàu. Nhà nghỉ có 15 phòng, tất cả đều được trang bị nội thất cơ bản. Nhà nghỉ Bãi Trước là một nơi lý tưởng để tiết kiệm chi phí khi du lịch Vũng Tàu. có sân hiên tắm nắng. Chỗ nghỉ có sân chơi cho trẻ em và tiện nghi BBQ trong khi du khách có thể chơi golf ở khu vực gần đó. Các điểm tham quan nổi tiếng gần chỗ nghỉ bao gồm Bạch Dinh, Khu du lịch sinh thái và văn hóa Hồ Mây cũng như Sân vận động Lam Sơn. Sân bay gần nhất là sân bay Vũng Tàu, cách Seaside - Bãi Trước Villa 4 km.',N'rabbit',112),
(8, N'Nhà nghỉ Hải Đăng',N'Nhà nghỉ Hải Đăng là một nhà nghỉ bình dân nằm ở trung tâm thành phố Vũng Tàu. Nhà nghỉ có 20 phòng, tất cả đều được trang bị nội thất cơ bản. Nhà nghỉ Hải Đăng là một nơi lý tưởng để tiết kiệm chi phí khi du lịch Vũng Tàu.
Tọa lạc bên cạnh bãi biển Mũi Né – bãi biển đẹp thơ mộng với cát trắng mịn, những rặng dừa xanh rì Resort Hải Đăng Phan Thiết đang dần trở thành một khu nghỉ dưỡng uy tín, chất lượng và thu hút nhiều du khách đến nghỉ dưỡng ở đây.
Đây là khu resort 2 sao quốc tế – một địa điểm phù hợp cho mọi đối tượng du khách. Du khách sẽ được tận hưởng không khí trong lành, được ngắm cảnh biển trong xanh và gạt bỏ đi được những muộn phiền, lo lắng trong lòng ở khu nghỉ dưỡng bình yên này. ',N'goidsh',115),
(11,N'Khách sạn Mường Thanh Holiday Huế', N'Muong Thanh Holiday Hue Hotel toạ lạc tại khu vực / thành phố Phú Hội.
khách sạn sở hữu vị trí đắc địa cách sân bay Sân bay quốc tế Phú Bài (HUI) 13,91 km.
khách sạn nằm cách Hue Railway Station 2,16 km.8
Có rất nhiều điểm tham quan lân cận như Kinh Thành Huế ở khoảng cách 1,5 km, và Bãi biển Thuận An ở khoảng cách 11,93 km.',N'lalalla',185),
(12,N'White Lotus Hue Hotel', N'Lưu trú tại White Lotus Hue Hotel là một lựa chọn đúng đắn khi quý khách đến thăm Phú Nhuận.
khách sạn sở hữu vị trí đắc địa cách sân bay Sân bay quốc tế Phú Bài 13,86 km.
khách sạn nằm cách Hue Railway Station 1,67 km.
khách sạn này rất dễ tìm bởi vị trí đắc địa, nằm gần với nhiều tiện ích công cộng.',N'nhonnhip',196),
(13,N' Rosamia Da Nang Hotel',N'Tận hưởng dịch vụ đỉnh cao, đẳng cấp thế giới tại Rosamia Da Nang Hotel. Nằm ở thành phố Đà Nẵng, cách Bãi biển Mỹ Khê vài bước chân, Rosamia Da Nang Hotel cung cấp chỗ nghỉ với trung tâm thể dục, chỗ đỗ xe riêng miễn phí, sân hiên và nhà hàng. Khách sạn 5 sao này cung cấp WiFi miễn phí, dịch vụ phòng và dịch vụ lễ tân 24 giờ. Khách sạn có hồ bơi trong nhà, phòng xông hơi khô, CLB đêm và CLB trẻ em., Tất cả phòng nghỉ tại Rosamia Da Nang Hotel được bố trí máy điều hòa, khu vực ghế ngồi, TV truyền hình cáp màn hình phẳng, két an toàn, ấm đun nước cũng như phòng tắm riêng đi kèm vòi sen, đồ vệ sinh cá nhân miễn phí và máy sấy tóc. Một số phòng có ban công trong khi các phòng còn lại nhìn ra quang cảnh thành phố. Mỗi phòng đều được trang bị ga trải giường và khăn tắm. Chỗ nghỉ phục vụ bữa sáng kiểu lục địa, bữa sáng kiểu Mỹ hoặc bữa sáng kiểu Á hằng ngày. Du khách có thể chơi ném phi tiêu và thuê xe hơi tại khách sạn 5 sao này. Trong khuôn viên chỗ nghỉ có quầy bar và du khách cũng có thể sử dụng khu dịch vụ văn phòng. Chỗ nghỉ nằm cách Bãi biển Bắc Mỹ An 1,1 km và Cầu khóa Tình yêu 3,2 km. Sân bay gần nhất là sân bay quốc tế Đà Nẵng, nằm trong bán kính 7 km từ Rosamia Da Nang Hotel, và chỗ nghỉ cung cấp dịch vụ đưa đón sân bay với một khoản phụ phí.' ,N'rỉeao',250),
(14,N'Mercure Danang French Village Bana Hills.',N' Mercure Danang French Village Bana Hills toạ lạc tại khu vực / thành phố Hòa Ninh.
Có rất nhiều điểm tham quan lân cận như Trường mầm non A Vương ở khoảng cách 46,58 km, và Trường THPT Quang Trung ở khoảng cách 39,45 km.',N'nanggyw',245),
(29, N'Mekong Lodge Hotel', N'<h2>Giới thiệu Mekong Lodge Hotel </h2><br><h3>Vị trí</h3><br> Mekong Lodge Hotel Tiền Giang là một khách sạn nằm trong khu vực an ninh, toạ lạc tại Xã Đông Hòa Hiệp. Chỉ cách Hồ Chí Minh 120 km về phía Tây Nam, khoảng 2,5 giờ lái xe, chúng ta sẽ thoát hoàn toàn khỏi thành phố náo nhiệt để đến một thế giới khác: thế giới của nước và thảm thực vật tươi tốt, một thế giới nơi con người có cuộc sống thư thái và hạnh phúc bên nhau. Cái Bè là hình ảnh đặc trưng của đồng bằng sông Cửu Long: chợ nổi nhộn nhịp, làng nghề truyền thống và vườn cây ăn quả. Mekong Lodge ẩn mình giữa những vườn xoài, nhãn, chôm chôm, sầu riêng và hoa xum xuê.  <h3>Thông tin về Mekong Lodge Hotel Tiền Giang</h3><br> Để đến được Mekong Lodge, cách duy nhất là bằng thuyền vì nó nằm trên một hòn đảo được bồi đắp bởi sông Tiền. Ở đây, thuyền là phương tiện di chuyển phổ biến nhất của người dân địa phương để di chuyển từ nơi này đến nơi khác. Mekong Lodge có 26 Bungalow riêng tư quyến rũ và Nhà hàng ven sông, trải dài trên diện tích hơn 20.000 m2. Ý tưởng của chúng tôi đã có từ rất lâu và giấc mơ của chúng tôi đã thành hiện thực vào tháng 11 năm 2010. Mekong Lodge hiện đã sẵn sàng chào đón những du khách đang tìm kiếm một chuyến khám phá thực sự ở Đồng bằng sông Cửu Long. Mekong Lodge là Khu nghỉ dưỡng sinh thái duy nhất ở Đồng bằng sông Cửu Long ở thời điểm hiện tại! Mekong Lodge là cơ sở lưu trú đầu tiên cam kết và tham gia đầy đủ vào Du lịch có trách nhiệm tại Đồng bằng sông Cửu Long, Việt Nam. Chúng tôi xây dựng những ngôi nhà gỗ và dịch vụ xanh mang đến cho du khách những trải nghiệm thú vị về Đồng bằng sông Cửu Long cũng như góp phần phát triển bền vững môi trường và cộng đồng địa phương.',N'iuiuyi',505),
(30, N' Sông Tiền Hotel', N'<h2>Giới thiệu Sông Tiền Hotel </h2><br><h3>Vị trí</h3><br> Khách sạn Sông Tiền Annex – tọa lạc tại số 33 Trưng Trắc – Phường 1, nằm ngay tuyến đường chính của trung tâm thành phố, mặt tiền hướng ra Sông Tiền, cách Bến tàu du lịch và chợ Mỹ Tho chỉ vài phút đi bộ chỉ vài phút đi bộ. Khách sạn được nâng cấp hoàn toàn vào tháng 04/2018, với 20 phòng ngủ sang trọng đầy đủ tiện nghi. <h3>Thông tin về Sông Tiền Hotel Tiền Giang </h3><br> Ngay sân thượng của khách sạn là nơi lý tưởng bậc nhất để ngắm nhìn toàn cảnh thành phố cũng như cả vùng sông nước mênh mông với các cù lao xanh mượt giữa dòng sông Tiền hiền hòa.',N'holy',510),
(31, N'LARA Long Xuyên Hotel',N'<h2>Giới thiệu LARA Long Xuyên </h2><br><h3>Vị trí</h3><br>
ARA HOTEL LONG XUYEN là một khách sạn nằm trong khu vực an ninh, toạ lạc tại Phường Mỹ Long.
Không chỉ sở hữu vị trí đắc địa, LARA HOTEL LONG XUYEN còn là một trong những khách sạn nằm cách Ancient House of Huynh Thuy Le chưa đầy 36,96 km và Binh Thuy Temple chưa đầy 48,16 km.<h3>Thông tin về LARA Long Xuyên </h3><br>
Dịch vụ tuyệt vời, cơ sở vật chất hoàn chỉnh và các tiện nghi khách sạn cung cấp sẽ khiến quý khách không thể phàn nàn trong suốt kỳ lưu trú tại LARA HOTEL LONG XUYEN.
Quầy tiếp tân 24 giờ luôn sẵn sàng phục vụ quý khách từ thủ tục nhận phòng đến trả phòng hay bất kỳ yêu cầu nào. Nếu cần giúp đỡ xin hãy liên hệ đội ngũ tiếp tân, chúng tôi luôn sẵn sàng hỗ trợ quý khách.Sóng WiFi phủ khắp các khu vực chung của khách sạn cho phép quý khách luôn kết nối với gia đình và bè bạn.
Với những tiện nghi sẵn có LARA HOTEL LONG XUYEN thực sự là một nơi lưu trú hoàn hảo.',N'fox',550),
(32, N'Đăng Khoa 2 Hotel',N'<h2>Giới thiệu Đăng Khoa 2 Hotel</h2><br><h3>Vị trí</h3><br>
Dang Khoa 2 Hotel toạ lạc tại khu vực / thành phố Núi Sam.
khách sạn nằm cách Chau Doc Ferry Terminal 5,59 km.
Có rất nhiều điểm tham quan lân cận như Đền Bà Chúa Xứ ở khoảng cách 0,35 km, và Rừng Trà Sư ở khoảng cách 11,2 km.
<h3>Thông tin về Đăng Khoa 2 Hotel </h3><br>
Dang Khoa 2 Hotel là lựa chọn thông thái nhất cho những ai đang tìm kiếm một khách sạn với dịch vụ xuất sắc nhưng hợp với túi tiền.
Dang Khoa 2 Hotel là lựa chọn lý tưởng cho những ai đang tìm kiếm một phòng nghỉ thoải mái với giá thành hợp lý.',N'chaudoctoi',542),
(33,N' Hà Giang Xanh Hotel',N'<h2>Giới thiệu Hà Giang Xanh Hotel</h2><br><h3>Vị trí</h3><br>
Lưu trú tại Hà Giang Xanh Homestay là một lựa chọn đúng đắn khi quý khách đến thăm phường Quang Trung.
nơi nghỉ này rất dễ tìm bởi vị trí đắc địa, nằm gần với nhiều tiện ích công cộng.
<h3>Thông tin về Hà Giang Xanh Hotel</h3><br>
Tận hưởng những món ăn yêu thích với phong cách ẩm thực đặc biệt từ Hà Giang Xanh Homestay chỉ dành riêng cho quý khách.
Hãy sẵn sàng đón nhận những giây phút vô giá khó phai trong suốt kỳ nghỉ của quý khách tại Hà Giang Xanh Homestay.',N'joiuytf',602),
(34, N' Odyssey Hotel', N'<h2>Giới thiệu Odyssey Hotel</h2><br><h3>Vị trí</h3><br>
Odyssey Hostel, Tours & Motorbikes Rental là một nơi nghỉ nằm trong khu vực an ninh, toạ lạc tại phường Nguyễn Trãi.
Không chỉ sở hữu vị trí đắc địa, Odyssey Hostel, Tours & Motorbikes Rental còn là một trong những nơi nghỉ nằm cách Rừng thông Yên Minh chưa đầy 40,96 km và Hoa Tam Giác Mạch chưa đầy 24,26 km
<h3>Thông tin về Odyssey Hotel</h3><br>
Tận hưởng những món ăn yêu thích với phong cách ẩm thực đặc biệt từ Odyssey Hostel, Tours & Motorbikes Rental chỉ dành riêng cho quý khách.
Odyssey Hostel, Tours & Motorbikes Rental là lựa chọn sáng suốt dành cho những du khách ghé thăm phường Nguyễn Trãi.',N'iugyu',605),
(35,N' Pu Luong Hotel', N'<h2>Giới thiệu Pu Luong Hotel</h2><br><h3>Vị trí</h3><br>
Lưu trú tại Pu Luong Ecocharm là một lựa chọn đúng đắn khi quý khách đến thăm Bá Thước.
nơi nghỉ này rất dễ tìm bởi vị trí đắc địa, nằm gần với nhiều tiện ích công cộng.
<h3>Thông tin về Pu Luong Hotel</h3><br>
Du lịch một mình cũng không hề kém phần thú vị và Pu Luong Ecocharm là nơi thích hợp dành riêng cho những ai đề cao sự riêng tư trong kỳ lưu trú.
Pu Luong Ecocharm là lựa chọn đúng đắn cho những ai đang tìm kiếm các nơi nghỉ hợp với túi tiền tại Bá Thước.',N'hodyu',612),
(36,N' Kingsales Hotel Thanh Hoa ',N'<h2>Giới thiệu Kingsales Hotel Thanh Hoa </h2><br><h3>Vị trí</h3><br>
Kingsales Hotel Thanh Hoa toạ lạc tại khu vực / thành phố Phường Đông Hương.
Có rất nhiều điểm tham quan lân cận như Thành nhà Hồ ở khoảng cách 35,2 km, và Động Từ Thức ở khoảng cách 33,27 km.
<h3>Thông tin về Kingsales Thanh Hoa Hotel</h3><br>
Du lịch một mình cũng không hề kém phần thú vị và Kingsales Hotel Thanh Hoa là nơi thích hợp dành riêng cho những ai đề cao sự riêng tư trong kỳ lưu trú.
Dịch vụ tuyệt vời, cơ sở vật chất hoàn chỉnh và các tiện nghi khách sạn cung cấp sẽ khiến quý khách không thể phàn nàn trong suốt kỳ lưu trú tại Kingsales Hotel Thanh Hoa.',N'ladtay',616),
(37,N' MeKong Quang Tri Hotel', N'<h2>Giới thiệu MeKong Quang Tri Hotel</h2><br><h3>Vị trí</h3><br>
Khách sạn Mê Kông Quảng Trị là khách sạn 3 sao tọa lạc tại vị trí trung tâm của thành phố Đông Hà, cách chợ Đông Hà khoảng 0.5 km, cách ga tàu 0.7 km, cách các điểm tham quan nỗi tiếng của tỉnh nhà như Thành cổ Quảng Trị, Cầu Hiền Lương - sông Bến Hải, nghĩa trang Quốc gia Đường 9, nghĩa trang Quốc gia Trường Sơn khoảng 15km – 20 km..<h3>Thông tin về MeKong Quang Tri Hotel</h3><br>Chỗ nghỉ có 73 phòng đạt tiêu chuẩn quốc tế gồm 50 phòng đạt chuẩn 3 sao, 23 phòng đạt chuẩn 2 sao, thoáng mát đầy đủ tiện nghi. Các phòng đều được trang bị TV truyền hình cáp/vệ tinh, máy điều hòa, bồn tắm cá nhân, minibar. ',N'mekong',668),
(38, N'  Công Đoàn Quảng Trị Hotel',N'<h2>Giới thiệu Công Đoàn Hotel</h2><br><h3>Vị trí</h3><br>
Lưu trú tại Công Đoàn Quảng Trị Hotel là một lựa chọn đúng đắn khi quý khách đến thăm .
Khách sạn này rất dễ tìm bởi vị trí đắc địa, nằm gần với nhiều tiện ích công cộng
<h3>Thông tin về Công Đoàn Luxury Hotel</h3><br>
Phòng rộng rãi thoải mái, wifi miễn phí, đỗ xe ô tô/xe máy thuận tiện.',N'nanguihj',670),
(39,N' Aloha Hotel Quy Nhơn',N'<h2>Giới thiệu Trong Dong Hotel</h2><br><h3>Vị trí</h3><br>
Aloha Hotel Quy Nhon là một khách sạn nằm trong khu vực an ninh, toạ lạc tại Phường Lê Lợi.
Không chỉ sở hữu vị trí đắc địa, Aloha Hotel Quy Nhon còn là một trong những khách sạn nằm cách Green Island chưa đầy 20,61 km và Cù Lao Hòn Nần chưa đầy 28,01 km.
<h3>Thông tin về Trong Dong Hotel</h3><br>
Aloha Hotel Quy Nhon là đề xuất hàng đầu dành cho những tín đồ du lịch ""bụi"" mong muốn được nghỉ tại một khách sạn vừa thoải mái lại hợp túi tiền.
Dành cho những du khách muốn du lịch thoải mái cùng ngân sách tiết kiệm, Aloha Hotel Quy Nhon sẽ là lựa chọn lưu trú hoàn hảo, nơi cung cấp các tiện nghi chất lượng và dịch vụ tuyệt vời.',N'thaduiuy',699),
(40,N' Muong Thanh Quy Nhon Hotel', N'<h2>Giới thiệu Muong Thanh Quy Nhon Hotel</h2><br><h3>Vị trí</h3><br>
Muong Thanh Quy Nhon Hotel là một khách sạn nằm trong khu vực an ninh, toạ lạc tại Phường Lê Lợi.
Không chỉ sở hữu vị trí đắc địa, Muong Thanh Quy Nhon Hotel còn là một trong những khách sạn nằm cách Mang Lang Church chưa đầy 48,7 km và Ghenh Rang Park chưa đầy 4,22 km.
<h3>Thông tin về Muong Thanh Quy Nhon Hotel</h3><br>
Hãy tận hưởng thời gian vui vẻ cùng cả gia đình với hàng loạt tiện nghi giải trí tại Muong Thanh Quy Nhon Hotel, một khách sạn tuyệt vời phù hợp cho mọi kỳ nghỉ bên người thân.
Nếu dự định có một kỳ nghỉ dài, thì Muong Thanh Quy Nhon Hotel chính là lựa chọn dành cho quý khách. Với đầy đủ tiện nghi với chất lượng dịch vụ tuyệt vời, Muong Thanh Quy Nhon Hotel sẽ khiến quý khách cảm thấy thoải mái như đang ở nhà vậy.',N'bumbum',705),
(41, N' Khang Hy Hotel',N'<h2>Giới thiệu Khang Hy Hotel</h2><br><h3>Vị trí</h3><br> Khách sạn này rất dễ tìm bởi vị trí đắc địa, nằm gần với nhiều tiện ích công cộng. <h3>Thông tin về Khang Hy Hotel</h3><br> Khang Hyi Hotel là lựa chọn sáng giá dành cho những ai đang tìm kiếm một trải nghiệm xa hoa đầy thú vị trong kỳ nghỉ của mình. Lưu trú tại đây cũng là cách để quý khách chiều chuộng bản thân với những dịch vụ xuất sắc nhất và khiến kỳ nghỉ của mình trở nên thật đáng nhớ. Tọa lạc gần sân bay, Khang Hy Hotel là nơi nghỉ ngơi lý tưởng trong lúc quý khách đang chờ chuyến bay kế tiếp. Quý khách có thể tận hưởng không gian nghỉ dưỡng vừa ý nơi đây trong quá trình quá cảnh.',N'cgvhdaw',737),
(42,N' Thanh Mai Hotel',N'<h2>Giới thiệu Thanh Mai Hotel</h2><br><h3>Vị trí</h3><br> Lưu trú tại Thanh Mai Hotel là một lựa chọn đúng đắn khi quý khách đến thăm Phường Tân An. khách sạn này rất dễ tìm bởi vị trí đắc địa, nằm gần với nhiều tiện ích công cộng. <h3>Thông tin về Thanh Mai Hotel</h3><br> Thanh Mai Hotel là lựa chọn sáng giá dành cho những ai đang tìm kiếm một trải nghiệm xa hoa đầy thú vị trong kỳ nghỉ của mình. Lưu trú tại đây cũng là cách để quý khách chiều chuộng bản thân với những dịch vụ xuất sắc nhất và khiến kỳ nghỉ của mình trở nên thật đáng nhớ. Tọa lạc gần sân bay, Thanh Mai Hotel là nơi nghỉ ngơi lý tưởng trong lúc quý khách đang chờ chuyến bay kế tiếp. Quý khách có thể tận hưởng không gian nghỉ dưỡng vừa ý nơi đây trong quá trình quá cảnh.',N'hayhi',742),
(43,N'Meliá Vinpearl Tây Ninh – Khách sạn có tầm nhìn đẹp ngay trung tâm thành phố',N'Tọa lạc ngay giữa trung tâm thành phố Tây Ninh, cách thành phố Hồ Chí Minh chưa đến 100 km, Meliá Vinpearl Tây Ninh sở hữu lối kiến trúc hiện đại và tinh tế với nhiều phòng nghỉ mang phong cách châu Âu cùng tầm nhìn tuyệt hảo ra thành phố hay núi Bà Đen sừng sững qua những ô cửa kính lớn. Đây là điểm đến lý tưởng để khám phá vẻ đẹp đích thực của Tây Ninh.',N'totpto',788),
(44,N'Hoàng Mai Hotel – Khách sạn 1 sao với mức giá vừa túi tiền',N'Các căn phòng được bày trí gọn gàng, sạch sẽ cùng các tiện nghi như wifi, TV, điều hòa và truyền hình cáp. Tuyệt vời hơn, bạn còn có thể thưởng thức bữa ăn cùng những người thân yêu tại khu sân vườn đầy ắp cây xanh này nữa đấy! Nếu bạn là người yêu thích thiên nhiên và sự đơn giản thì hãy đặt chỗ tại Hoàng Mai Hotel ngay thôi nào!',N'Kkday',763),
(45,N'Khách sạn Sao Mai',N'Xét về cơ sở hạ tầng và cung phương pháp phục vụ của những khách sạn "tại xứ sở sen hồng", sở hữu thể kể khách sạn Sao Mai là một trong những khách sạn thấp nhất tại Đồng Tháp. Hằng năm khách sạn 3 sao này không chỉ đón tiếp lượng lớn khách du lịch mà còn là nơi những quan chức cao cấp, thương nhân xẹp thăm mỗi lúc có  công việc tại thành phố Cao Lãnh.',N'Khachsanvietnamtoi',811),
(46,N'Chuỗi khách sạn B.O.B',N'Chuỗi khách sạn B.O.B là một trong những khách sạn top đầu ở Đồng Tháp. Tuy mới được xây dựng và đưa vào hoạt động gần đây nhưng Chuỗi khách sạn B.O.B đã tạo được không ít tiếng vang và trở thành khách sạn thu hút khách bậc nhất ở xứ sen hồng. Nằm trong chuỗi phức hợp nhà hàng – khách sạn – cà phê sang trọng B.O.B, Chuỗi khách sạn B.O.B đem đến cho khách du lịch cơ hội trải nghiệm không gian sang trọng và đẳng cấp.',N'Alongwalker',827),
(47,N'Khách sạn Mường Thanh Luxury Cà Mau',N'Được nhận xét điểm 10 cho chất lượng từ cách điệu phục vụ đến cơ sở vật chất, khách sạn Cà Mau sang trọng bậc nhất Mường Thanh Luxury chắc chắn đem đến sự đảm bảo và an tâm không những cho các du khách mà còn cho những người kinh doanh đang công tác tại Cà Mau. Đội ngũ nhiều những nhân viên nhiệt tình, hòa nhã. Vị trí thuận lợi cho việc đi lại, thăm quan mua sắm trong thành phố, khách sạn Cà Mau 5 sao Mường Thanh Luxury chắc chắn sẽ không làm du khách thất vọng.',N'SapaVietNam',850),
(48,N'Sao Kim Hotel Cà Mau',N'Khách sạn nằm trong tòa nhà VNPT với số lượng phòng tương đối để phù hợp cho khách đi công tác, khách đi du lịch cặp đôi, gia đình. Khách sạn nằm tại trung tâm nên view có thể ngắm cảnh thành phố xung quanh. Khách sạn có phục vụ bữa sáng miễn phí cho khách nghỉ tại Sao Kim, xung quanh cũng có nhiều chỗ ăn uống rất tiện lợi cho khách đi công tác.',N'Mrvivu',838),
(49,N'Ben Tre Riverside Resort',N'Một khách sạn ở Bến Tre được đánh giá cao bởi sự sang trọng, hiện đại không nơi nào khác đó là Ben Tre Riverside Resort. Nơi đây sở hữu khung cảnh thiên nhiên mát lạnh, cảnh quan thơ mộng. DU khách sẽ được đắm chìm trong không gian yên bình ngắm nhìn sông nước. Và du khách còn có cơ hội đón ánh bình minh dưới tán lá dừa, tận hưởng làn gió mát ở Ben Tre Riverside Resort.',N'Halotravel',889),
(50,N'DIAMOND STARS BEN TRE HOTEL',N'Nhắc đến những khách sạn ở Bến Tre sang trọng, nổi tiếng thì không thể bỏ qua DIAMOND STARS BEN TRE HOTEL. Đây là khách sạn tiêu chuẩn 4 sao với thiết kế ban công riêng hiện đại. DIAMOND STARS kết hợp hoàn hảo giữa không gian nghỉ dưỡng cao cấp, xen lẫn những nét giản dị của xứ dừa. Đặc biệt, đứng ở những tầng trên của khách sạn, du khách có thể ngắm nhìn quang cảnh của thành phố.',N'Halotravel',898),
(51,N'White Palace Thái Bình',N'Tọa lạc tại trung tâm thành phố Thái Bình, White Palace Thái Bình là một trong những khách sạn đáng lưu trú nhất mà bạn nên cân nhắc khi ghé thăm miền đất phương Bắc này. Khách sạn đạt tiêu chuẩn 3 sao, hệ thống cơ sở vật chất, tiện nghi đáp ứng đầy đủ. Lựa chọn nghỉ dưỡng tại White Palace Thái Bình, bạn sẽ có được những phút giây nghỉ ngơi thoải mái.',N'Gody',922),
(52,N'Petro Thai Binh Hotel',N'Petro Thai Binh Hotel là một lựa chọn tuyệt vời cho khách du lịch khi đến thăm Thái Bình, mang đến những tiện nghi hữu ích cho suốt thời gian lưu trú của bạn. Là “ngôi nhà xa xứ,” các phòng khách sạn cung cấp điều hòa nhiệt độ và quầy bar mini, và kết nối mạng thật dễ dàng, với wifi miễn phí sẵn có. Khách có thể dùng bàn lễ tân 24 giờ, dịch vụ phòng và nhân viên hỗ trợ khách khi nghỉ tại Petro Thai Binh Hotel.',N'Tripadvior',928),
(53,N'Mường Thanh Luxury Cao Bằng',N'Lưu trú tại Muong Thanh Luxury Cao Bang là một lựa chọn đúng đắn khi quý khách đến thăm Phường Hợp Giang. Quầy tiếp tân 24 giờ luôn sẵn sàng phục vụ quý khách từ thủ tục nhận phòng đến trả phòng hay bất kỳ yêu cầu nào. Nếu cần giúp đỡ xin hãy liên hệ đội ngũ tiếp tân, chúng tôi luôn sẵn sàng hỗ trợ quý khách. Sóng WiFi phủ khắp các khu vực chung của khách sạn cho phép quý khách luôn kết nối với gia đình và bè bạn.',N'Tripadvior',937),
(54,N'Khách sạn Luxury',N'Luxury Hotel là một khách sạn nằm trong khu vực an ninh, toạ lạc tại Phường Hợp Giang. Quầy tiếp tân 24 giờ luôn sẵn sàng phục vụ quý khách từ thủ tục nhận phòng đến trả phòng hay bất kỳ yêu cầu nào. Nếu cần giúp đỡ xin hãy liên hệ đội ngũ tiếp tân, chúng tôi luôn sẵn sàng hỗ trợ quý khách.',N'SapaVietNam',952),
(55,N'Khách Sạn Cherry Hotel Bến Lức – Thiên Đường Nghỉ Dưỡng Dành Cho Bạn',N'Khách Sạn Cherry Hotel Bến Lức là thiên đường nghỉ dưỡng khách sạn Long An dành cho bạn khi bạn đặt chân tới đây. Nơi đây có vị trí tuyệt vời ngay tại trung tâm khu vực. Khách sạn này nằm gần chợ và khu dân cư, mang lại sự thuận tiện tuyệt đối cho quý khách trong những chuyến đi công tác. Khách Sạn Cherry Hotel Bến Lức mang đến cho quý khách trải nghiệm hoàn toàn mới với nội thất sang trọng và hiện đại. Đội ngũ nhân viên trẻ trung, năng động và chuyên nghiệp luôn sẵn sàng phục vụ và làm hài lòng bạn. Nơi đây mang đến cho quý khách những dịch vụ chất lượng và chế độ hậu mãi tốt. Sự thoải mái và sự hài lòng của quý khách là ưu tiên hàng đầu của khách sạn.',N'Inhat',982),
(56,N'Khách Sạn Làng Nổi Tân Lập – Địa Chỉ Khách Sạn Long An Đẹp',N'Khách Sạn Làng Nổi Tân Lập là một điểm đến lý tưởng cho những ai muốn tận hưởng không gian thiên nhiên và trải nghiệm vẻ đẹp chân thật miền Tây sông nước. Với vị trí tại Làng Nổi Tân Lập, khách sạn này mang đến cho du khách một trải nghiệm độc đáo và khác biệt. Khi đến với Khách Sạn Làng Nổi Tân Lập, bạn sẽ cảm nhận được sự yên tĩnh và thoáng mát của không gian xung quanh. Đây là khách sạn Long An lý tưởng để tận hưởng những ngày nghỉ dưỡng dài ngày. Nơi bạn có thể thả lỏng tâm hồn và tránh xa sự ồn ào của thành phố.',N'Inhat',978),
(57,N'Khách sạn Bombo-Những khách sạn ở Bình Phước giá tốt chất lượng cao',N'Khách sạn này có vị trí vô cùng thuận lợi để di chuyển đến các điểm du lịch, tham quan, ăn uống cũng như mua sắm tại đây. Bomboo cũng được đánh giá là khách sạn chất lượng, có giá tốt nhất ở Bình Phước. Nó không chỉ sở hữu view nhìn cực đẹp, có thể bao quát cả thành phố mà dịch vụ rất hoàn hảo. Bomboo hotel mang đến không gian nghỉ ngơi lý tưởng với đầy đủ tiện nghi cao cấp. Khu vực sân vườn của khách sạn này khá rộng vời nhiều cây cảnh, chậu hoa nhiều màu sắc. Các tiểu cảnh trang trí khá độc đáp và bắt mắt. Tất cả tạo cảm giác thỏa mái, dễ chịu và tràn đầy sức sống.',N'Alongwalker',1024),
(58,N'Khách sạn Mỹ Lệ',N'Một trong những khách sạn ở Bình Phước được đánh giá rất tốt chính là Mỹ Lệ Hotel. Vị trí tọa lạc thuận lợi của khách sạn này khiến du khách rất thích lưu trú tại đây. Từ khách sạn, bạn sẽ không mất quá nhiều thời gian để di chuyển đến các điểm tham quan nổi tiếng ở Bình Phước như sóc Bom Bo, vườn quốc gia Bù Mập, thác Voi, khu du lịch Sóc Xiêm, núi Bà Rá, thác Mơ,… Bên cạnh đó, xung quanh khách sạn cũng có khá nhiều nhà hàng, trung tâm mua sắm lớn giúp bạn thỏa mái lựa chọn trong việc ăn uống, mua sắm.',N'Dulichbinhphuoc',1021),
(59,N'Khách sạn Sài Gòn – Vĩnh Long',N'Đây là lựa chọn hàng đầu của nhiều du khách khi đến Vĩnh Long. Khách sạn nằm ngay tại trung tâm thành phố, chỉ cách Bảo tàng khoảng 500 m nên rất thuận tiện để thăm quan, khám phá. Nhờ thiết kế sang trọng và quầy lễ tân phục vụ chu đáo 24/7 mà Sài Gòn – Vĩnh Long luôn được chắc đến với tiêu chuẩn 4 sao tiện nghi bậc nhất.',N'Kkday',1069),
(60,N'Riverside Park Eco Hotel & Resort',N'Đến với Riverside Park Eco Resort, bạn sẽ được hòa mình vào thiên nhiên ngay giữa lòng thành phố bởi rừng cây xanh bao bọc. Không khí cũng vô cùng trong lành và mát mẻ. Tận hưởng thêm nhiều tiện ích tuyệt vời như nhà hàng sang trọng, bãi đỗ xe miễn phí, hồ bơi ngoài trời thoáng đãng và quầy bar sành điệu. Và đặc biệt hơn là ở mỗi phòng ngủ đều có sân hiên dành riêng cho du khách tắm nắng với tầm nhìn ra sân vườn xanh mát, thích hợp để bạn nghỉ dưỡng và thư giãn sau những chuỗi ngày làm việc mệt mỏi.',N'Mrvivu',1080)