INSERT INTO PLACE VALUES
(N'Đà Lạt'),
(N'Nha Trang'),
(N'Phan Thiết'),
(N'Vũng Tàu'),
(N'Phú Quốc'),
(N'Huế'),
(N'Đà Nẵng'),
(N'Sapa'),
(N'Ninh Bình'),
(N'Hạ Long'),
(N'Cần Thơ'),
(N'Phú Yên'),
(N'Hà Nội'),
(N'Thành phố Hồ Chí Minh'),
(N'Tiền Giang'),
(N'An Giang'),
(N'Hà Giang'),
(N'Thanh Hóa'),
(N'Quảng Trị'),
(N'Bình Định'),
(N'Buôn Ma Thuột'),
(N'Tây Ninh'),
(N'Đồng Tháp'),
(N'Cà Mau'),
(N'Bến Tre'),
(N'Thái Bình'),
(N'Cao Bằng'),
(N'Long An'),
(N'Bình Phước'),
(N'Vĩnh Long')
